sudo: false
language: node_js
node_js:
  # List 'lts/*' as last entry because on this we'll trigger the release.
  - "6"
  - "8"
  - "lts/*"
before_script:
  # Use DEBUG mode to ensure more accurate tests.
  - export "DEBUG=1"
after_success:
  - set -e
  - if [ "$TRAVIS_NODE_VERSION" = "lts/*" -a "$TRAVIS_BRANCH" == "master" ]; then bash ./release.sh; fi
